version: 2
jobs:
  deploy-demo:
    docker:
      - image: opuscapita/ci-node8:latest

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: init-ci-container
          command: /ci-scripts/init.sh

      - run:
          name: lerna-init
          command: yarn --ignore-scripts

      - run:
          name: docker-login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: docker-build
          command: npm run docker:build

      - run:
          name: docker-publish
          command: npm run docker:publish


workflows:
  version: 2

  commit:
      jobs:
        - build

        - deploy-demo:
            requires:
              - build
